# Generated by Django 4.2.3 on 2023-07-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done']},
        ),
    ]
