# Generated by Django 4.2.3 on 2023-07-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-done']},
        ),
    ]
