# Generated by Django 4.2.3 on 2023-07-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='is_done',
        ),
    ]
